/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JWindow;
import javax.swing.SwingUtilities;

/**
 *
 * @author robert
 */
public class DisciplinaItemPanel extends javax.swing.JPanel {

    Disciplina disciplina;
    
    /**
     * Creates new form ProfessorPanel
     */
    public DisciplinaItemPanel(Disciplina disciplina) {
        initComponents();
        this.disciplina = disciplina;
        nomeLabel.setText(disciplina.getNome());
        creditosLabel.setText(disciplina.getCreditos().toString() + " Creditos");
        periodoLabel.setText(disciplina.getPeriodo().toString() + "º Periodo");
        turmasListPanel.add(new ListPanel((List<Turma>)disciplina.getTurmaCollection()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        nomeLabel = new javax.swing.JLabel();
        creditosLabel = new javax.swing.JLabel();
        periodoLabel = new javax.swing.JLabel();
        turmasListPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomeLabel.setText("Nome");

        creditosLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        creditosLabel.setText("Creditos");

        periodoLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        periodoLabel.setText("Periodo");

        turmasListPanel.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(creditosLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(turmasListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodoLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(creditosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodoLabel)
                    .addComponent(turmasListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );
    }//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBorder(null);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditosLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel periodoLabel;
    private javax.swing.JPanel turmasListPanel;
    // End of variables declaration//GEN-END:variables
}
