/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

/**
 *
 * @author robert
 */
public class GradeHorariosPanel extends javax.swing.JPanel {

    Grade grade;
    
    /**
     * Creates new form GradeHorariosPanel
     */
    public GradeHorariosPanel(Grade grade) {
        initComponents();
        this.grade = grade;
        nomeGradeLabel.setText(grade.getNome());
        initHorariosPanels();
    }

    private void initHorariosPanels(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        nomeGradeLabel = new javax.swing.JLabel();
        horariosPanel = new javax.swing.JPanel();
        linhaHorasLabel = new javax.swing.JLabel();
        diasListPanel = new javax.swing.JPanel();
        segundaPanel = new javax.swing.JPanel();
        segundaLabel = new javax.swing.JLabel();
        tercaPanel = new javax.swing.JPanel();
        segundaLabel1 = new javax.swing.JLabel();
        quartaPanel = new javax.swing.JPanel();
        segundaLabel2 = new javax.swing.JLabel();
        quintaPanel = new javax.swing.JPanel();
        segundaLabel3 = new javax.swing.JLabel();
        sextaPanel = new javax.swing.JPanel();
        segundaLabel4 = new javax.swing.JLabel();
        sabadoPanel = new javax.swing.JPanel();
        segundaLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nomeGradeLabel.setText("Nome Grade");

        horariosPanel.setBackground(new java.awt.Color(255, 255, 255));

        linhaHorasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gradeinteligente/images/linhaHoras.png"))); // NOI18N

        diasListPanel.setBackground(new java.awt.Color(255, 255, 255));
        diasListPanel.setLayout(new java.awt.GridLayout(6, 0));

        segundaPanel.setBackground(new java.awt.Color(255, 255, 255));
        segundaPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel.setText("Segunda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 949);
        segundaPanel.add(segundaLabel, gridBagConstraints);

        diasListPanel.add(segundaPanel);

        tercaPanel.setBackground(new java.awt.Color(255, 255, 255));
        tercaPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel1.setText("Terça");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 973);
        tercaPanel.add(segundaLabel1, gridBagConstraints);

        diasListPanel.add(tercaPanel);

        quartaPanel.setBackground(new java.awt.Color(255, 255, 255));
        quartaPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel2.setText("Quarta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 963);
        quartaPanel.add(segundaLabel2, gridBagConstraints);

        diasListPanel.add(quartaPanel);

        quintaPanel.setBackground(new java.awt.Color(255, 255, 255));
        quintaPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel3.setText("Quinta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 964);
        quintaPanel.add(segundaLabel3, gridBagConstraints);

        diasListPanel.add(quintaPanel);

        sextaPanel.setBackground(new java.awt.Color(255, 255, 255));
        sextaPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel4.setText("Sexta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 971);
        sextaPanel.add(segundaLabel4, gridBagConstraints);

        diasListPanel.add(sextaPanel);

        sabadoPanel.setBackground(new java.awt.Color(255, 255, 255));
        sabadoPanel.setLayout(new java.awt.GridBagLayout());

        segundaLabel5.setText("Sábado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 12, 31, 959);
        sabadoPanel.add(segundaLabel5, gridBagConstraints);

        diasListPanel.add(sabadoPanel);

        javax.swing.GroupLayout horariosPanelLayout = new javax.swing.GroupLayout(horariosPanel);
        horariosPanel.setLayout(horariosPanelLayout);
        horariosPanelLayout.setHorizontalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horariosPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(linhaHorasLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(horariosPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(diasListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        horariosPanelLayout.setVerticalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linhaHorasLabel)
                .addGap(0, 0, 0)
                .addComponent(diasListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nomeGradeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(horariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeGradeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diasListPanel;
    private javax.swing.JPanel horariosPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel linhaHorasLabel;
    private javax.swing.JLabel nomeGradeLabel;
    private javax.swing.JPanel quartaPanel;
    private javax.swing.JPanel quintaPanel;
    private javax.swing.JPanel sabadoPanel;
    private javax.swing.JLabel segundaLabel;
    private javax.swing.JLabel segundaLabel1;
    private javax.swing.JLabel segundaLabel2;
    private javax.swing.JLabel segundaLabel3;
    private javax.swing.JLabel segundaLabel4;
    private javax.swing.JLabel segundaLabel5;
    private javax.swing.JPanel segundaPanel;
    private javax.swing.JPanel sextaPanel;
    private javax.swing.JPanel tercaPanel;
    // End of variables declaration//GEN-END:variables
}
