/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

import java.awt.GridBagConstraints;
import java.io.Serializable;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author robert
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel(List<? extends Serializable> list) {
        if(list.isEmpty())
            return;
        
        initComponents();
        
        int i = 0;
        
        this.setAutoscrolls(true);
        
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.ipady = 0;
        c.ipadx = 0;
        c.gridwidth = 1;
        c.gridx = 0;
        
        for(Serializable item: list){
            JPanel itemPanel = createPanelByType(item);
            c.gridy = i;        
            this.add(itemPanel, c);
            i++;
        }
    }
    
    private JPanel createPanelByType(Serializable entity){
        if(entity instanceof Professor)
            return new ProfessorItemPanel((Professor) entity);
        if(entity instanceof Turma)
            return new TurmaItemPanel((Turma) entity);
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
