/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.io.Serializable;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author robert
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel(List<?> list) {
        if(list.isEmpty())
            return;
        
        initComponents();
        
        this.setAutoscrolls(true);
        ((GridLayout)this.getLayout()).setRows(list.size()<15? 15:list.size());
        
        
        for(Object item: list){
            if(item == null)
                continue;
            JPanel itemPanel = createPanelByType(item);
            this.add(itemPanel);
        }
    }
    
    private JPanel createPanelByType(Object entity){
        if(entity instanceof Professor)
            return new ProfessorItemPanel((Professor) entity);
        if(entity instanceof Turma)
            return new TurmaItemPanel((Turma) entity);
        if(entity instanceof Disciplina)
            return new DisciplinaItemPanel((Disciplina) entity);
        if(entity instanceof JLabel){
            JPanel panel = new JPanel();
            panel.add((JLabel) entity);
            return panel;
        }
        
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(100, 1));
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
