/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

import java.awt.Color;
import java.awt.GridLayout;

/**
 *
 * @author robert
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lateralPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        mainGradePanel = new javax.swing.JPanel();
        mainTurmasPanel = new javax.swing.JPanel();
        mainProfessoresPanel = new javax.swing.JPanel();
        mainSalasPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        gradePanel = new javax.swing.JPanel();
        gradeLabel = new javax.swing.JLabel();
        turmasPanel = new javax.swing.JPanel();
        turmasLabel = new javax.swing.JLabel();
        professoresPanel = new javax.swing.JPanel();
        professoresLabel = new javax.swing.JLabel();
        salasPanel = new javax.swing.JPanel();
        salasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lateralPanel.setBackground(new java.awt.Color(188, 75, 81));
        lateralPanel.setLayout(new java.awt.GridLayout(10, 1));

        jPanel5.setBackground(new java.awt.Color(188, 75, 81));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Criar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lateralPanel.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(188, 75, 81));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apagar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lateralPanel.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(188, 75, 81));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Editar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lateralPanel.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(188, 75, 81));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Visualizar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lateralPanel.add(jPanel8);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new javax.swing.OverlayLayout(mainPanel));

        mainGradePanel.setBackground(new java.awt.Color(188, 75, 81));
        mainGradePanel.setEnabled(false);
        mainGradePanel.setFocusable(false);
        mainGradePanel.setOpaque(false);

        javax.swing.GroupLayout mainGradePanelLayout = new javax.swing.GroupLayout(mainGradePanel);
        mainGradePanel.setLayout(mainGradePanelLayout);
        mainGradePanelLayout.setHorizontalGroup(
            mainGradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        mainGradePanelLayout.setVerticalGroup(
            mainGradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        mainPanel.add(mainGradePanel);

        mainTurmasPanel.setBackground(new java.awt.Color(140, 179, 105));
        mainTurmasPanel.setEnabled(false);
        mainTurmasPanel.setFocusable(false);
        mainTurmasPanel.setOpaque(false);

        javax.swing.GroupLayout mainTurmasPanelLayout = new javax.swing.GroupLayout(mainTurmasPanel);
        mainTurmasPanel.setLayout(mainTurmasPanelLayout);
        mainTurmasPanelLayout.setHorizontalGroup(
            mainTurmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainTurmasPanelLayout.setVerticalGroup(
            mainTurmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(mainTurmasPanel);

        mainProfessoresPanel.setBackground(new java.awt.Color(244, 226, 133));
        mainProfessoresPanel.setEnabled(false);
        mainProfessoresPanel.setFocusable(false);
        mainProfessoresPanel.setOpaque(false);

        javax.swing.GroupLayout mainProfessoresPanelLayout = new javax.swing.GroupLayout(mainProfessoresPanel);
        mainProfessoresPanel.setLayout(mainProfessoresPanelLayout);
        mainProfessoresPanelLayout.setHorizontalGroup(
            mainProfessoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        mainProfessoresPanelLayout.setVerticalGroup(
            mainProfessoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        mainPanel.add(mainProfessoresPanel);

        mainSalasPanel.setBackground(new java.awt.Color(244, 162, 89));

        javax.swing.GroupLayout mainSalasPanelLayout = new javax.swing.GroupLayout(mainSalasPanel);
        mainSalasPanel.setLayout(mainSalasPanelLayout);
        mainSalasPanelLayout.setHorizontalGroup(
            mainSalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainSalasPanelLayout.setVerticalGroup(
            mainSalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(mainSalasPanel);

        menuPanel.setLayout(new java.awt.GridLayout(1, 4));

        gradePanel.setBackground(new java.awt.Color(188, 75, 81));

        gradeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradeLabel.setText("Grade");
        gradeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gradePanelLayout = new javax.swing.GroupLayout(gradePanel);
        gradePanel.setLayout(gradePanelLayout);
        gradePanelLayout.setHorizontalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        gradePanelLayout.setVerticalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanel.add(gradePanel);

        turmasPanel.setBackground(new java.awt.Color(140, 179, 105));

        turmasLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        turmasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turmasLabel.setText("Turmas");
        turmasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turmasLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout turmasPanelLayout = new javax.swing.GroupLayout(turmasPanel);
        turmasPanel.setLayout(turmasPanelLayout);
        turmasPanelLayout.setHorizontalGroup(
            turmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turmasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turmasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        turmasPanelLayout.setVerticalGroup(
            turmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turmasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turmasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanel.add(turmasPanel);

        professoresPanel.setBackground(new java.awt.Color(244, 226, 133));

        professoresLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        professoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        professoresLabel.setText("Professores");
        professoresLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                professoresLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout professoresPanelLayout = new javax.swing.GroupLayout(professoresPanel);
        professoresPanel.setLayout(professoresPanelLayout);
        professoresPanelLayout.setHorizontalGroup(
            professoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        professoresPanelLayout.setVerticalGroup(
            professoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanel.add(professoresPanel);

        salasPanel.setBackground(new java.awt.Color(244, 162, 89));

        salasLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salasLabel.setText("Salas");
        salasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salasLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salasPanelLayout = new javax.swing.GroupLayout(salasPanel);
        salasPanel.setLayout(salasPanelLayout);
        salasPanelLayout.setHorizontalGroup(
            salasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        salasPanelLayout.setVerticalGroup(
            salasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanel.add(salasPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lateralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(12,98,145));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(new Color(188,75,81));
    }//GEN-LAST:event_jPanel5MouseExited

    private void gradeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeLabelMouseClicked
        openTab(mainGradePanel);
    }//GEN-LAST:event_gradeLabelMouseClicked

    private void turmasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turmasLabelMouseClicked
        openTab(mainTurmasPanel);
    }//GEN-LAST:event_turmasLabelMouseClicked

    private void professoresLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professoresLabelMouseClicked
        openTab(mainProfessoresPanel);
    }//GEN-LAST:event_professoresLabelMouseClicked

    private void salasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salasLabelMouseClicked
        openTab(mainSalasPanel);
    }//GEN-LAST:event_salasLabelMouseClicked

    private void openTab(javax.swing.JPanel panelToOpen) {
        mainTurmasPanel.setEnabled(false);
        mainTurmasPanel.setFocusable(false);
        mainTurmasPanel.setVisible(false);
        mainTurmasPanel.setOpaque(false);
        mainGradePanel.setEnabled(false);
        mainGradePanel.setFocusable(false);
        mainGradePanel.setVisible(false);
        mainGradePanel.setOpaque(false);
        mainProfessoresPanel.setEnabled(false);
        mainProfessoresPanel.setFocusable(false);
        mainProfessoresPanel.setVisible(false);
        mainProfessoresPanel.setOpaque(false);
        mainSalasPanel.setEnabled(false);
        mainSalasPanel.setFocusable(false);
        mainSalasPanel.setVisible(false);
        mainSalasPanel.setOpaque(false);
        panelToOpen.setEnabled(true);
        panelToOpen.setFocusable(true);
        panelToOpen.setVisible(true);
        panelToOpen.setOpaque(true);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel lateralPanel;
    private javax.swing.JPanel mainGradePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainProfessoresPanel;
    private javax.swing.JPanel mainSalasPanel;
    private javax.swing.JPanel mainTurmasPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel professoresLabel;
    private javax.swing.JPanel professoresPanel;
    private javax.swing.JLabel salasLabel;
    private javax.swing.JPanel salasPanel;
    private javax.swing.JLabel turmasLabel;
    private javax.swing.JPanel turmasPanel;
    // End of variables declaration//GEN-END:variables
}
