/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

import java.awt.GridBagConstraints;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;

/**
 *
 * @author robert
 */
public class TurmasListPanel extends javax.swing.JPanel {

    /**
     * Creates new form TurmasPanel
     */
    public TurmasListPanel(List<Turma> turmas) {
        initComponents();
        int i = 0;
        this.setAutoscrolls(true);
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.ipady = 0;
        c.ipadx = 0;
        c.gridwidth = 1;
        c.gridx = 0;
        
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;        
            this.add(turmaPanel, c);
            i++;
        }
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        
        for(Turma turma: turmas){
            JPanel turmaPanel = new TurmaPanel(turma);
            c.gridy = i;    
            
            this.add(turmaPanel, c);
            i++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.rowHeights = new int[] {60};
        setLayout(layout);
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
