/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradeinteligente;

/**
 *
 * @author robert
 */
public class TurmaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TurmaPanel
     */
    public TurmaPanel(Turma turma) {
        initComponents();
        nomeDisciplinaLabel.setText(turma.getDisciplina().toString());
        nomeProfessorLabel.setText(turma.getProfessor().toString());
        creditosLabel.setText(turma.getDisciplina().getCreditos().toString());
        //periodoLabel.setText(turma.getDisciplina().getPeriodo().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        nomeDisciplinaLabel = new javax.swing.JLabel();
        nomeProfessorLabel = new javax.swing.JLabel();
        creditosLabel = new javax.swing.JLabel();
        periodoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nomeDisciplinaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomeDisciplinaLabel.setText("Disciplina");

        nomeProfessorLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nomeProfessorLabel.setText("Professor");

        creditosLabel.setText("Creditos");

        periodoLabel.setText("Periodo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nomeProfessorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(periodoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeDisciplinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(creditosLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDisciplinaLabel)
                    .addComponent(creditosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProfessorLabel)
                    .addComponent(periodoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditosLabel;
    private javax.swing.JLabel nomeDisciplinaLabel;
    private javax.swing.JLabel nomeProfessorLabel;
    private javax.swing.JLabel periodoLabel;
    // End of variables declaration//GEN-END:variables
}
